# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b3d0eacfd754fcfed4369f4385f09df824987b2d5a762a5dc81b4b4a0f2c3603aeba525120e068c9495403904e53181457e3ba4073abc1ca7e5bc94949df71d

test:
  secret_key_base: bbbbb3616d44c786e530aa37ff619ee5c7b69487f5a20f7163c105bfdd051eb01ad3a52eddcafc27f8d966a03bf8d3c417be828d7676b59b01ecd922f900ee97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
